src/objects/Boutique_Resource__c.object
<CustomObject>
    <fields>
        <fullName>Boutique__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Boutique</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Boutique Resource</relationshipLabel>
        <relationshipName>Boutique_Resource</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Boutique Resource</relationshipLabel>
        <relationshipName>Boutique_Resource</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Boutique Resource</label>
    <nameField>
        <label>Boutique Resource Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Boutique Resource</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/selectors/BoutiqueResourceSelector.cls
/**
 * Created by Mariya on 14.11.2022.
 */

public inherited sharing class BoutiqueResourceSelector {

    public static Boutique_Resource__c getBoutiqueResourceById(Id boutiqueId) {
        return [SELECT Id FROM Boutique_Resource__c WHERE Id = :boutiqueId];
    }

    public static List<Boutique_Resource__c> getBoutiqueResourceByContactIds(Set<Id> contactIds) {
        return [SELECT Name, Boutique__c, Contact__c FROM Boutique_Resource__c WHERE Contact__c IN :contactIds];
    }

    public static List<Boutique_Resource__c> getBoutiqueResourceByUserIds(Set<Id> userIds) {
        return [SELECT User__c, Id, RecordTypeId FROM Boutique_Resource__c WHERE User__c IN :userIds];
    }
}