src/objects/Weather__c.object
<CustomObject>
    <fields>
        <fullName>Date_and_Time__c</fullName>
        <label>Date and Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Humidity__c</fullName>
        <label>Humidity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Temperature__c</fullName>
        <label>Max Temperature</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Temperature__c</fullName>
        <label>Min Temperature</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pressure__c</fullName>
        <label>Pressure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Temp__c</fullName>
        <label>Temperature</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Weather</label>
    <nameField>
        <label>Weather Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/selectors/WeatherSelector.cls
/**
 * Created by Mariya on 12.12.2022.
 */

public inherited sharing class WeatherSelector {

    public static List<Weather__c> getById(String id) {
        return [
                SELECT Name, Date_and_Time__c, Pressure__c, Humidity__c, Temp__c, Min_Temperature__c, Max_Temperature__c
                FROM Weather__c
                WHERE Id = :id
        ];
    }

    public static List<Weather__c> getByYear(String year) {

        List<Weather__c> weathers = new List<Weather__c>();

        for (Weather__c item : [SELECT Date_and_Time__c from Weather__c WHERE Date_and_Time__c != NULL]) {
            if (item.Date_and_Time__c.year() == Integer.valueOf(year)) {
                weathers.add(item);
            }
        }

        return weathers;
    }
}