src/objects/Weather__c.object
<CustomObject>
    <fields>
        <fullName>Humidity__c</fullName>
        <label>Humidity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Temperature__c</fullName>
        <label>Max Temperature</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Temperature__c</fullName>
        <label>Min Temperature</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Pressure__c</fullName>
        <label>Pressure</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Temp__c</fullName>
        <label>Temperature</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wind_Speed__c</fullName>
        <label>Wind Speed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Weather</label>
    <nameField>
        <label>Weather Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Weather</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/controllers/OpenWeatherController.cls
/**
 * Created by Mariya on 30.11.2022.
 */

public with sharing class OpenWeatherController {

    public static String getWeatherByCityName (String cityName) {
        String urlData = 'data/2.5/weather?q='+cityName;
        Map<String, String> apiKeyMap = new Map<String, String>{'x-api-key' => 'c840127ab41a64ffc77361a9d11b3ab3'};

        return HttpService.makeHttpRequest(
                'callout:OpenWeatherNamedCredential', urlData, 'GET', apiKeyMap);

    }

    public static String getWeatherByCityId (String cityId) {
        String callout = 'callout:OpenWeatherNamedCredential';
        String urlData = 'data/2.5/weather?&id=702550';
        String method = 'GET';
        Map<String, String> apiKeyMap = new Map<String, String>{'x-api-key' => 'c840127ab41a64ffc77361a9d11b3ab3'};

        return HttpService.makeHttpRequest(callout, urlData, method, apiKeyMap);
    }

    public static void saveWeather(String responseData){
        OpenWeatherDto.fromJSON data = OpenWeatherDto.parse(responseData);

        Weather__c weatherRecord = new Weather__c();
        weatherRecord.Name = data.name ;
        weatherRecord.Humidity__c = data.main.humidity ;
        weatherRecord.Max_Temperature__c = data.main.temp_max ;
        weatherRecord.Min_Temperature__c = data.main.temp_min ;
        weatherRecord.Pressure__c = data.main.pressure ;
        weatherRecord.Temp__c = data.main.temp ;
        weatherRecord.Wind_Speed__c = data.wind.speed ;

        insert weatherRecord;
    }
}